version: '3.1'

services:
  adobackend:
    image: anaellejeagni/ado_backend:optimized-v3
    deploy:
      mode: replicated
      replicas : 3
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
      restart_policy:
        condition: on-failure    
    volumes:
      - ./log/backend:/log/backend
    healthcheck:
      test: ["CMD", "curl -f http://127.0.0.1:8080/welcome || exit 1"]
      timeout: 30s
      interval: 5m
      retries: 3
  adofrontend:
    image: anaellejeagni/ado_frontend:optimized-v4
    ports:
      - "8081:8081"
    volumes:
      - ./log/frontend:/log/frontend
    deploy:
      mode: replicated
      replicas : 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
      restart_policy:
        condition: on-failure    
    links:
      - adobackend
    environment:
      - backend.url=http://adobackend:8080/
    healthcheck:
      test: ["CMD", "curl -f http://127.0.0.1:8081 || exit 1"]
      timeout: 30s
      interval: 5m
      retries: 3
