server:
  port: 8080
logging:
  file:
    name: ./log/ado_backend.log
app:
  name: backend api
  description: you are on the front that call the back server by docker image
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
