apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: adofrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adofrontend
  template:
    metadata:
      labels:
        app: adofrontend
    spec:
      containers:
        - name: adofrontend
          image: anaellejeagni/ado_frontend:optimized-v4
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          ports:
          - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10
          env:
            - name: backend.url
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: backend-url

