#SERVICE CONFIGURATION
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: adobackend
  ports:
    - protocol: TCP
      port: 8080 #Service port
      targetPort: 8080 #containerPort of deployment