apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: adobackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adobackend
  template:
    metadata:
      labels:
        app: adobackend
    spec:
      containers:
        - name: adobackend
          image: anaellejeagni/ado_backend:optimized-v4
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10
          env:
            - name: app.description
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: app_description
            - name: app.name
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: app_name
